[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

# Remappings for ETHFALCON contracts compatibility
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts-upgradeable/lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

# Optimizer settings matching verified contract
optimizer = true
optimizer_runs = 10000

# EVM version matching verified contract
evm_version = "cancun"

# File system permissions for test files
fs_permissions = [
    { access = "read", path = "./test/test_vectors/" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
